#!/usr/bin/env bash
# scripts/setup_notebook.sh
# Path: cs1090b_HallucinationLegalRAGChatbots/scripts/setup_notebook.sh
# Responsibility: notebook integration — repro env, repro module, stability, kernel.
# Sourced by setup.sh — defines functions only, no top-level execution.

write_repro_env() {
    _require_project_root
    echo " Writing reproducibility .env..."
    cat > "${PROJECT_ROOT}/.env" << ENVEOF
# .env
# Path: cs1090b_HallucinationLegalRAGChatbots/.env
# Reproducibility environment variables — source this before running experiments.
# Generated by setup.sh — do not edit manually.
# Load in notebooks via: import dotenv; dotenv.load_dotenv()
# Load in shell via:     set -a && source .env && set +a
export PYTHONHASHSEED=${REPRO_PYTHONHASHSEED}
export CUBLAS_WORKSPACE_CONFIG=${REPRO_CUBLAS_CFG}
export TOKENIZERS_PARALLELISM=${REPRO_TOKENIZERS_PAR}
export RANDOM_SEED=${RANDOM_SEED}
ENVEOF
    [ ! -f "${PROJECT_ROOT}/.env" ] && {
        _msg_error ".env not created" "cat heredoc to .env failed" \
            "Notebooks cannot load reproducibility settings" \
            "Check disk space and permissions on ${PROJECT_ROOT}"
        exit 1
    }
    _require_python
    $PYTHON -c "
import os
checks=[('PYTHONHASHSEED','${REPRO_PYTHONHASHSEED}'),
        ('CUBLAS_WORKSPACE_CONFIG','${REPRO_CUBLAS_CFG}'),
        ('TOKENIZERS_PARALLELISM','${REPRO_TOKENIZERS_PAR}'),
        ('RANDOM_SEED','${RANDOM_SEED}')]
failed=[]
for var,exp in checks:
    act=os.environ.get(var)
    if act!=exp: failed.append(f'{var}={act!r} != {exp!r}')
    else: print(f'  \033[0;32m✓\033[0m {var}={act}')
if failed:
    print('\033[0;31m  ✗ Env var mismatch — check ~/.bashrc for overrides\033[0m')
    for f in failed: print(f'    {f}')
    raise SystemExit(1)
"
}

write_repro_module() {
    _require_python; _require_repro_env
    echo " Writing src/repro.py — notebook/CLI parity module..."
    mkdir -p "${PROJECT_ROOT}/src"
    cat > "${PROJECT_ROOT}/src/repro.py" << PYEOF
# src/repro.py
# Path: cs1090b_HallucinationLegalRAGChatbots/src/repro.py
#
# Canonical reproducibility configuration module.
# Call configure() as the FIRST statement in every notebook Cell 1 and CLI script.
#
# Why this exists:
#   setup.sh sets env vars in the shell. The Jupyter kernel launches fresh — it
#   inherits nothing. This module is the single source of truth that both notebook
#   and CLI import to get identical settings regardless of launch method.
#
# Usage:
#   from src.repro import configure
#   repro_cfg = configure()  # must be FIRST — before any torch import
#
# RANDOM_SEED injected from scripts/lib.sh constants.
# To change: update RANDOM_SEED in scripts/lib.sh, re-run bash setup.sh, commit.
import os
import random
import logging
from pathlib import Path
from typing import Optional

logger = logging.getLogger(__name__)

_EXPECTED_PYTHONHASHSEED  = "${REPRO_PYTHONHASHSEED}"
_EXPECTED_CUBLAS_CFG      = "${REPRO_CUBLAS_CFG}"
_EXPECTED_TOKENIZERS_PAR  = "${REPRO_TOKENIZERS_PAR}"
_RANDOM_SEED              = ${RANDOM_SEED}


def _load_dotenv(project_root: Optional[Path] = None) -> None:
    """Load .env. Single responsibility: env var loading only."""
    root = project_root or Path(__file__).resolve().parent.parent
    env_path = root / ".env"
    if not env_path.exists():
        raise FileNotFoundError(
            f".env not found at {env_path}.\n"
            f"  Why: Required for reproducibility settings in all processes.\n"
            f"  Fix: bash setup.sh from the project root."
        )
    try:
        from dotenv import load_dotenv
        load_dotenv(env_path, override=False)
    except ImportError:
        with open(env_path) as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    key, _, val = line.partition("=")
                    key = key.replace("export ", "").strip()
                    val = val.strip()
                    if key not in os.environ:
                        os.environ[key] = val


def _apply_torch_flags() -> None:
    """Apply deterministic torch settings. Single responsibility: flag application only."""
    import torch
    os.environ.setdefault("CUBLAS_WORKSPACE_CONFIG", _EXPECTED_CUBLAS_CFG)
    torch.use_deterministic_algorithms(True, warn_only=False)
    torch.backends.cudnn.benchmark = False
    torch.backends.cudnn.deterministic = True


def _seed_all(seed: int) -> None:
    """Seed all RNGs. Single responsibility: seeding only."""
    random.seed(seed)
    try:
        import numpy as np; np.random.seed(seed)
    except ImportError:
        pass
    try:
        import torch
        torch.manual_seed(seed)
        if torch.cuda.is_available():
            torch.cuda.manual_seed_all(seed)
    except ImportError:
        pass


def _verify() -> dict:
    """Verify all settings are active. Single responsibility: verification only."""
    import torch
    checks = {}
    for var, expected in [
        ("PYTHONHASHSEED",          _EXPECTED_PYTHONHASHSEED),
        ("CUBLAS_WORKSPACE_CONFIG", _EXPECTED_CUBLAS_CFG),
        ("TOKENIZERS_PARALLELISM",  _EXPECTED_TOKENIZERS_PAR),
    ]:
        actual = os.environ.get(var)
        if actual != expected:
            raise AssertionError(
                f"{var}={actual!r} — expected {expected!r}.\n"
                f"  Why: Must be set before importing torch.\n"
                f"  Fix: Call configure() as the VERY FIRST statement in Cell 1."
            )
        checks[var] = actual
    if not torch.are_deterministic_algorithms_enabled():
        raise AssertionError(
            "torch.use_deterministic_algorithms not enabled.\n"
            "  Fix: Call configure() before any torch import, or re-run Cell 1."
        )
    checks["deterministic_algorithms"] = True
    if torch.backends.cudnn.benchmark:
        raise AssertionError("cudnn.benchmark=True.\n  Fix: re-run Cell 1.")
    checks["cudnn_benchmark"] = False
    if not torch.backends.cudnn.deterministic:
        raise AssertionError("cudnn.deterministic=False.\n  Fix: re-run Cell 1.")
    checks["cudnn_deterministic"] = True
    checks["random_seed"] = _RANDOM_SEED
    return checks


def configure(
    project_root: Optional[Path] = None,
    verbose: bool = True,
) -> dict:
    """
    Thin orchestrator: load → apply → seed → verify.
    Call as the FIRST statement in every notebook Cell 1 and CLI script.
    Returns verified config dict for logging/manifest inclusion.
    """
    _load_dotenv(project_root)
    _apply_torch_flags()
    _seed_all(_RANDOM_SEED)
    cfg = _verify()
    if verbose:
        import torch
        print("  [repro] Reproducibility configured:")
        for k, v in cfg.items():
            print(f"    {k}={v}")
        if torch.cuda.is_available():
            print(f"    torch.cuda.manual_seed_all({_RANDOM_SEED}) → {torch.cuda.device_count()} GPU(s)")
    return cfg
PYEOF
    [ ! -f "${PROJECT_ROOT}/src/repro.py" ] && {
        _msg_error "src/repro.py not created" "File not found after write" \
            "Notebooks will fail to import configure()" \
            "Check disk/permissions on ${PROJECT_ROOT}/src/"
        exit 1
    }
    _msg_ok "src/repro.py written (RANDOM_SEED=${RANDOM_SEED})"
    $PYTHON -c "
import sys; sys.path.insert(0,'${PROJECT_ROOT}')
from src.repro import configure
cfg = configure(verbose=True)
assert cfg['random_seed'] == ${RANDOM_SEED}
print('  \033[0;32m✓\033[0m src/repro.configure() verified')
" || {
        _msg_error "src/repro.py verification failed" "configure() raised after write" \
            "Notebooks will run without reproducibility settings" \
            "DEBUG=1 STEP=write_repro_module bash setup.sh"
        exit 1
    }
}

verify_numerical_stability() {
    _require_python; _require_repro_env
    echo " Verifying numerical/runtime stability..."
    $PYTHON -c "
import os, torch, sys
checks=[
    ('CUBLAS_WORKSPACE_CONFIG',os.environ.get('CUBLAS_WORKSPACE_CONFIG'),'${REPRO_CUBLAS_CFG}'),
    ('PYTHONHASHSEED',os.environ.get('PYTHONHASHSEED'),'${REPRO_PYTHONHASHSEED}'),
    ('TOKENIZERS_PARALLELISM',os.environ.get('TOKENIZERS_PARALLELISM'),'${REPRO_TOKENIZERS_PAR}'),
    ('RANDOM_SEED',os.environ.get('RANDOM_SEED'),'${RANDOM_SEED}'),
]
torch.use_deterministic_algorithms(True, warn_only=False)
torch.backends.cudnn.benchmark = False
torch.backends.cudnn.deterministic = True
failed=[]
for name,actual,exp in checks:
    if actual!=exp: failed.append(f'{name}={actual!r} != {exp!r}')
    else: print(f'  \033[0;32m✓\033[0m {name}={actual}')
if not torch.are_deterministic_algorithms_enabled(): failed.append('deterministic_algorithms not enabled')
if torch.backends.cudnn.benchmark: failed.append('cudnn.benchmark=True')
if not torch.backends.cudnn.deterministic: failed.append('cudnn.deterministic=False')
if failed:
    print('\033[0;31m  ✗ Stability check FAILED:\033[0m')
    for f in failed: print(f'    • {f}')
    print('\033[0;36m  Fix: Check ~/.bashrc for env var overrides, then: bash setup.sh\033[0m')
    sys.exit(1)
print('  \033[0;32m✓\033[0m torch deterministic flags — ok')
print()
print('  \033[2mNOTE: Notebooks must call: from src.repro import configure; configure()\033[0m')
"
}

register_kernel() {
    _require_python
    echo " Registering Jupyter kernel..."
    $PYTHON -m ipykernel install --user \
        --name hallucination-legal-rag \
        --display-name "HallucinationLegalRAG (${TARGET_PYTHON_VERSION})"
    $PYTHON -m jupyter kernelspec list --json 2>/dev/null | $PYTHON -c "
import sys,json
data=json.load(sys.stdin)
kernels=data.get('kernelspecs',{})
if 'hallucination-legal-rag' not in kernels:
    print('\033[0;31m  ✗ ERROR — Kernel not found after registration\033[0m')
    print('    Why: JupyterLab will default to wrong kernel, missing venv packages')
    print('    Fix: STEP=register_kernel bash setup.sh')
    sys.exit(1)
spec=kernels['hallucination-legal-rag']
print(f'  \033[0;32m✓\033[0m kernel registered: {spec[\"spec\"][\"display_name\"]}')
print(f'    path: {spec[\"resource_dir\"]}')
" || _msg_warn "Kernel verification skipped" \
    "Could not verify via venv jupyter" "informational" \
    "Manually verify: .venv/bin/python -m jupyter kernelspec list"
}
